### ISSUE TITLE
Preferences not working

### ISSUE THREAD

**Issue by 1abd135** [roothide/Dopamine-roothide#6]
The preferences I set in the settings do not actually change the tool's preferences

No specific tweak,all of them 

I tried to reinstall preferenceloader and tweaks

And I previously copied the preferences from dopamine rootless to dopamine roothide

**Comment by RootHide** [comment]
just install PreferenceLoader in roothide repo in sileo.

and whats tweak you are talking about?

some tweaks are not updated for roothide and may not work perfectly.

join our discord to get more help: https://discord.gg/scqCkumAYp

**Comment by 1abd135** [comment]
It seems that only tweaks from roothide repo are work 
Even if I use roothide patcher

**Comment by RootHide** [comment]
> It seems that only tweaks from roothide repo are work Even if I use roothide patcher

RootHidePatcher with rootless compat layer works with most rootless tweaks now.
